class InvalidPhoneError(Exception):
    ...

class InvalidTypeError(Exception):
    ...

class InvalidKeysError(Exception):
    ...

class NotUniqueEmailError(Exception):
    ...

class NotUniquePhoneError(Exception):
    ...